name: Build and Deploy WAR to EC2 Tomcat

on:
  push:
    branches:
      - week5  # You can change this to your desired deployment branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR file with Maven
        working-directory: week5/mawakeb
        run: mvn clean package

      - name: Upload WAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: week5/mawakeb/target/jwp-basic.war
          target: /home/ec2-user/tomcat/webapps/

      - name: Restart Tomcat on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ~/tomcat/bin/shutdown.sh || true
            sleep 3
            ~/tomcat/bin/startup.sh
